# -*- coding: utf-8 -*-
"""Tugas Besar_Kecerdasan Buatan_Fuzzy Logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OexE49MFV1S6w5J9tadYme41J1SyZTqZ

# Laporan Tugas Besar Kecerdasan Buatan: Sistem Fuzzy Rekomendasi Bengkel
**Semester Ganjil 2025/2026**

---

### 1. Deskripsi Proyek
Proyek ini mengimplementasikan Fuzzy Logic, sebuah logika matematika yang memberikan nilai berdasarkan derajat kepercayaan. Sistem ini dirancang untuk mengolah data input menjadi keputusan rekomendasi di mana aturannya ditentukan oleh manusia untuk menjaga nilai kemanusiaan dalam sistem. Program ini dibangun menggunakan bahasa pemrograman Python dan dikembangkan sepenuhnya tanpa menggunakan Library sistem fuzzy eksternal.

### 2. Desain dan Analisis Sistem Fuzzy
Sesuai dengan spesifikasi tugas, berikut adalah rancangan sistem yang digunakan:

* **Atribut Input & Nama Linguistik:**
    * **Servis (0-100):** Buruk, Biasa, Bagus.
    * **Harga (1-10):** Murah, Sedang, Mahal.
* **Fungsi Keanggotaan:** Menggunakan kombinasi bentuk fungsi Trapesium (untuk kategori ekstrem seperti Buruk/Bagus dan Murah/Mahal) serta Segitiga (untuk kategori menengah seperti Biasa/Sedang).
* **Aturan Inferensi:** Menggunakan metode Sugeno dengan 9 aturan dasar yang memetakan kombinasi servis dan harga ke dalam kategori kelayakan.
* **Metode Defuzzifikasi:** Menggunakan metode Weighted Average (Rata-rata Terbobot).
* **Fungsi Keanggotaan Output:** Output direpresentasikan dalam nilai konstanta (singleton): Tidak Layak (20), Lumayan (60), dan Layak (100).

### 3. Implementasi Program
Seluruh proses berikut diimplementasikan secara manual melalui fungsi Python:
1.  **Membaca Data:** Membaca dataset bengkel dari file Excel.
2.  **Fuzzification:** Menghitung derajat keanggotaan input berdasarkan batas fungsi.
3.  **Inferensi:** Menerapkan aturan inferensi untuk mendapatkan nilai fuzzy output.
4.  **Defuzzification:** Menghitung skor kelayakan akhir bengkel.
5.  **Menyimpan Output:** Mengekspor hasil perankingan ke dalam file .xlsx baru.

---
"""

import pandas as pd
import numpy as np

# membuat data dummy untuk 100 bengkel
data = {
    'id': range(1, 101),
    'servis': np.random.randint(1, 101, 100), # Nilai 1-100
    'harga': np.random.randint(1, 11, 100)    # Nilai 1-10
}

# menyimpan ke Excel
df = pd.DataFrame(data)
df.to_excel('bengkel.xlsx', index=False)

print("File 'bengkel.xlsx' berhasil dibuat!")
print("Contoh data:")
print(df.head())

# --- Fungsi Fuzzifikasi Servis (0 - 100) ---
def fungsi_servis(x):
    # inisialisasi nilai derajat keanggotaan
    buruk = 0
    biasa = 0
    bagus = 0

    # 1. menghitung derajat buruk (trapesium turun: a=20, b=50)
    if x <= 20:
        buruk = 1
    elif 20 < x < 50:
        buruk = (50 - x) / (50 - 20)
    else:
        buruk = 0

    # 2. menghitung derajat biasa (segitiga: a=20, b=50, c=80)
    if 20 < x <= 50:
        biasa = (x - 20) / (50 - 20)
    elif 50 < x < 80:
        biasa = (80 - x) / (80 - 50)
    else:
        biasa = 0

    # 3. menghitung derajat bagus (trapesium naik: a=50, b=80)
    if x <= 50:
        bagus = 0
    elif 50 < x < 80:
        bagus = (x - 50) / (80 - 50)
    else:
        bagus = 1

    return buruk, biasa, bagus

# --- Fungsi Fuzzifikasi Harga (1 - 10) ---
def fungsi_harga(x):
    # inisialisasi
    murah = 0
    sedang = 0
    mahal = 0

    # 1. menghitung derajat murah (trapesium turun: a=2, b=7)
    if x <= 2:
        murah = 1
    elif 2 < x < 7:
        murah = (7 - x) / (7 - 2)
    else:
        murah = 0

    # 2. menghitung derajat sedang (segitiga: a=2, b=7, c=9)
    if 2 < x <= 7:
        sedang = (x - 2) / (7 - 2)
    elif 7 < x < 9:
        sedang = (9 - x) / (9 - 7)
    else:
        sedang = 0

    # 3. menghitung derajat mahal (trapesium naik: a=7, b=9)
    if x <= 7:
        mahal = 0
    elif 7 < x < 9:
        mahal = (x - 7) / (9 - 7)
    else:
        mahal = 1

    return murah, sedang, mahal

# --- Test Code ---
print("Cek Fuzzifikasi Servis nilai 75:")
print(fungsi_servis(75))

print("\nCek Fuzzifikasi Harga nilai 4:")
print(fungsi_harga(4))

# --- Fungsi Inferensi (Sugeno) ---
def inferensi(servis_cat, harga_cat):
    # Unpack nilai fuzzifikasi (pecah variabel biar pendek)
    s_buruk, s_biasa, s_bagus = servis_cat
    h_murah, h_sedang, h_mahal = harga_cat

    # Konstanta Output Sugeno
    TIDAK = 20   # Tidak Layak
    LUMA  = 60   # Lumayan
    LAYAK = 100  # Layak

    # List untuk menampung [alpha, nilai_z]
    rules = []

    # 1. Rules untuk Servis BAGUS
    rules.append([min(s_bagus, h_murah), LAYAK])  # Bagus & Murah -> Layak
    rules.append([min(s_bagus, h_sedang), LAYAK]) # Bagus & Sedang -> Layak
    rules.append([min(s_bagus, h_mahal), LUMA])   # Bagus & Mahal -> Lumayan

    # 2. Rules untuk Servis BIASA
    rules.append([min(s_biasa, h_murah), LAYAK])  # Biasa & Murah -> Layak
    rules.append([min(s_biasa, h_sedang), LUMA])  # Biasa & Sedang -> Lumayan
    rules.append([min(s_biasa, h_mahal), TIDAK])  # Biasa & Mahal -> Tidak Layak

    # 3. Rules untuk Servis BURUK
    rules.append([min(s_buruk, h_murah), LUMA])   # Buruk & Murah -> Lumayan
    rules.append([min(s_buruk, h_sedang), TIDAK]) # Buruk & Sedang -> Tidak Layak
    rules.append([min(s_buruk, h_mahal), TIDAK])  # Buruk & Mahal -> Tidak Layak

    return rules

# --- TEST CODE ---
# Cek logika sederhana
s_test = (0, 0.2, 0.8) # Contoh: Agak Bagus
h_test = (0.6, 0.4, 0) # Contoh: Agak Murah

print("Hasil Inferensi (Alpha, Z):")
print(inferensi(s_test, h_test))

import pandas as pd

# --- Fungsi Defuzzifikasi (Weighted Average) ---
def defuzzifikasi(rules):
    # Hitung (Alpha * Z) dan Total Alpha
    pembilang = sum(r[0] * r[1] for r in rules)
    penyebut = sum(r[0] for r in rules)

    # Mencegah pembagian nol
    return pembilang / penyebut if penyebut != 0 else 0

# --- PROGRAM UTAMA ---
# 1. Load Data
df = pd.read_excel('bengkel.xlsx')
hasil_skor = []

# 2. Loop Utama: Proses Fuzzy tiap baris
for i, row in df.iterrows():
    # Fuzzifikasi
    servis = fungsi_servis(row['servis'])
    harga = fungsi_harga(row['harga'])

    # Inferensi
    rules = inferensi(servis, harga)

    # Defuzzifikasi
    skor = defuzzifikasi(rules)
    hasil_skor.append(skor)

# 3. Simpan & Urutkan
df['skor'] = hasil_skor
df_sorted = df.sort_values(by='skor', ascending=False)

# 4. Ambil 5 Terbaik & Export
top5 = df_sorted.head(5)
top5.to_excel('top5_bengkel_terbaik.xlsx', index=False)

print("SUKSES! Berikut 5 Bengkel Terbaik Rekomendasi Sistem Fuzzy:")
print(top5)

"""---
### Kesimpulan dan Analisis Hasil

Berdasarkan pengujian terhadap dataset (termasuk pengujian dengan 500 data dummy untuk menguji skalabilitas), berikut adalah kesimpulan yang diperoleh:

* **Hasil Rekomendasi:** Sistem berhasil mengidentifikasi dan menampilkan daftar 5 bengkel terbaik pilihan sistem.
* **Kelengkapan Informasi:** Output program mencakup informasi lengkap berupa ID bengkel, kualitas servis, harga, dan skor kelayakannya.
* **Integritas Teknis:** Program berjalan dengan benar tanpa menggunakan library fuzzy pihak ketiga, sesuai dengan batasan penilaian tugas.
* **Efektivitas Metode:** Penggunaan metode Sugeno terbukti efektif dalam memberikan penilaian objektif untuk perankingan otomatis, di mana bengkel dengan skor kelayakan tertinggi adalah yang memiliki kualitas servis maksimal dan harga yang kompetitif.

**Hasil 5 bengkel terbaik telah disimpan ke dalam file 'top5_bengkel_terbaik.xlsx' sesuai instruksi.**
---
"""